# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
  - linux
julia:
  - 1.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: true 
